#include "Options1.h"
#include "Options.h"
#include <QStandardPaths>
#include <SDL_mixer.h>
#define readValue(name, type, defaultValue) \
    m_##name = value(#name, defaultValue).value<type>();
#define writeValue(name, value) \
    setValue(#name, value);

namespace OpenXcom
{
    QString openXComFolder()
    {
        QString pathToDocuments = QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation);
        return pathToDocuments + "/OpenXCom";
    }
    Options1::Options1():
        QSettings(openXComFolder()+"/Options1.cfg", IniFormat)
    {
        beginGroup("General");
            readValue(pauseMode,  qint32, 0)
            readValue(maxFPS, qint32, 60)
            readValue(maxFPSInactive, qint32, 30)
            readValue(pauseMode, qint32, 0)
            readValue(changeValueByMouseWheel, qint32, 0)
            readValue(dragScrollTimeTolerance, qint32, 300)
            readValue(dragScrollPixelTolerance, qint32, 10)
            readValue(mousewheelSpeed, qint32, 3)
            readValue(autosaveFrequency, qint32, 5)

			readValue(fullscreen, bool, false)
			readValue(asyncBlit, bool, false)
			readValue(playIntro, bool, false)
			readValue(useScaleFilter, bool, false)
			readValue(useHQXFilter, bool, false)
			readValue(useXBRZFilter, bool, false)
			readValue(useOpenGL, bool, false)
			readValue(checkOpenGLErrors, bool, false)
			readValue(vSyncForOpenGL, bool, true)
			readValue(useOpenGLSmoothing, bool, false)

			readValue(autosave, bool, true)
			readValue(allowResize, bool, false)
			readValue(borderless, bool, false)
			readValue(debug, bool, false)
			readValue(debugUi, bool, false)
			readValue(fpsCounter, bool, true)
			readValue(newSeedOnLoad, bool, false)
			readValue(keepAspectRatio, bool, true)
			readValue(nonSquarePixelRatio, bool, false)
			readValue(cursorInBlackBandsInFullscreen, bool, false)
			readValue(cursorInBlackBandsInWindow, bool, true)
			readValue(cursorInBlackBandsInBorderlessWindow, bool, true)
			readValue(maximizeInfoScreens, bool, true)
			readValue(musicAlwaysLoop, bool, false)
			readValue(stereoSound, bool, true)
			readValue(verboseLogging, bool, false)
			readValue(soldierDiaries, bool, true)
			readValue(touchEnabled, bool, false)
			readValue(rootWindowedMode, bool, false)
			readValue(lazyLoadResources, bool, true)
			readValue(backgroundMute, bool, true)

			readValue(language, QString, "")
			readValue(keyboardMode, KeyboardType, KEYBOARD_ON)
			readValue(saveOrder, SaveSort, SORT_DATE_DESC)
			readValue(preferredMusic, MusicFormat, MUSIC_AUTO)
			readValue(preferredSound, SoundFormat, SOUND_AUTO)
			readValue(preferredVideo, VideoFormat, VIDEO_FMV)
			readValue(captureMouse, SDL_GrabMode, 0)
			readValue(wordwrap, TextWrapping, WRAP_AUTO)
			readValue(keyOk, SDLKey, SDLK_RETURN)
			readValue(keyCancel, SDLKey, SDLK_ESCAPE)
			readValue(keyScreenshot, SDLKey, SDLK_F12)
			readValue(keyFps, SDLKey, SDLK_F7)
			readValue(keyQuickLoad, SDLKey, SDLK_F9)
			readValue(keyQuickSave, SDLKey, SDLK_F5)
			readValue(useOpenGLShader, QString, "Shaders/Raw.OpenGL.shader")
		endGroup();
		beginGroup("Geoscape");
			readValue(geoClockSpeed, qint32, 80)
			readValue(dogfightSpeed, qint32, 30)
			readValue(geoScrollSpeed, qint32, 20)
			readValue(geoDragScrollButton, qint32, SDL_BUTTON_LEFT)
			readValue(geoscapeScale, qint32, 0)
			readValue(includePrimeStateInSavedLayout, bool, false)
			readValue(anytimePsiTraining, bool, false)
			readValue(weaponSelfDestruction, bool, false)
			readValue(retainCorpses, bool, false)
			readValue(craftLaunchAlways, bool, false)
			readValue(globeSurfaceCache, bool, false)
			readValue(globeSeasons, bool, false)
			readValue(globeDetail, bool, true)
			readValue(globeRadarLines, bool, true)
			readValue(globeFlightPaths, bool, true)
			readValue(globeAllRadarsOnBaseBuild, bool, true)
			readValue(storageLimitsEnforced, bool, false)
			readValue(canSellLiveAliens, bool, false)
			readValue(canTransferCraftsWhileAirborne, bool, false)
			readValue(customInitialBase, bool, false)
			readValue(aggressiveRetaliation, bool, false)
			readValue(geoDragScrollInvert, bool, false)
			readValue(allowBuildingQueue, bool, false)
			readValue(showFundsOnGeoscape, bool, false)
			readValue(psiStrengthEval, bool, false)
			readValue(allowPsiStrengthImprovement, bool, false)
			readValue(fieldPromotions, bool, false)
			readValue(meetingPoint, bool, false)
			readValue(keyGeoLeft, SDLKey, SDLK_LEFT)
			readValue(keyGeoRight, SDLKey, SDLK_RIGHT)
			readValue(keyGeoUp, SDLKey, SDLK_UP)
			readValue(keyGeoDown, SDLKey, SDLK_DOWN)
			readValue(keyGeoZoomIn, SDLKey, SDLK_PLUS)
			readValue(keyGeoZoomOut, SDLKey, SDLK_MINUS)
			readValue(keyGeoSpeed1, SDLKey, SDLK_1)
			readValue(keyGeoSpeed2, SDLKey, SDLK_2)
			readValue(keyGeoSpeed3, SDLKey, SDLK_3)
			readValue(keyGeoSpeed4, SDLKey, SDLK_4)
			readValue(keyGeoSpeed5, SDLKey, SDLK_5)
			readValue(keyGeoSpeed6, SDLKey, SDLK_6)
			readValue(keyGeoIntercept, SDLKey, SDLK_i)
			readValue(keyGeoBases, SDLKey, SDLK_b)
			readValue(keyGeoGraphs, SDLKey, SDLK_g)
			readValue(keyGeoUfopedia, SDLKey, SDLK_u)
			readValue(keyGeoOptions, SDLKey, SDLK_ESCAPE)
			readValue(keyGeoFunding, SDLKey, SDLK_f)
			readValue(keyGeoToggleDetail, SDLKey, SDLK_TAB)
			readValue(keyGeoToggleRadar, SDLKey, SDLK_r)
			readValue(keyBaseSelect1, SDLKey, SDLK_1)
			readValue(keyBaseSelect2, SDLKey, SDLK_2)
			readValue(keyBaseSelect3, SDLKey, SDLK_3)
			readValue(keyBaseSelect4, SDLKey, SDLK_4)
			readValue(keyBaseSelect5, SDLKey, SDLK_5)
			readValue(keyBaseSelect6, SDLKey, SDLK_6)
			readValue(keyBaseSelect7, SDLKey, SDLK_7)
			readValue(keyBaseSelect8, SDLKey, SDLK_8)
		endGroup();
		beginGroup("Battlescape");
			readValue(battleEdgeScroll, ScrollType, SCROLL_AUTO)
			readValue(battleNewPreviewPath, PathPreview, PATH_NONE)
			readValue(battleScrollSpeed, qint32, 8)
			readValue(battleDragScrollButton, qint32, 0)
			readValue(battleFireSpeed, qint32, 6)
			readValue(battleXcomSpeed, qint32, 30)
			readValue(battleAlienSpeed, qint32, 30)
			readValue(battleExplosionHeight, qint32, 0)
			readValue(battlescapeScale, qint32, 0)

			readValue(traceAI, bool, false)
			readValue(sneakyAI, bool, false)
			readValue(battleInstantGrenade, bool, false)
			readValue(battleNotifyDeath, bool, false)
			readValue(battleTooltips, bool, true)
			readValue(battleHairBleach, bool, true)
			readValue(battleAutoEnd, bool, false)
			readValue(strafe, bool, false)
			readValue(forceFire, bool, true)
			readValue(showMoreStatsInInventoryView, bool, false)
			readValue(allowPsionicCapture, bool, false)
			readValue(skipNextTurnScreen, bool, false)
			readValue(disableAutoEquip, bool, false)
			readValue(battleDragScrollInvert, bool, false)
			readValue(battleUFOExtenderAccuracy, bool, false)
			readValue(battleConfirmFireMode, bool, false)
			readValue(battleSmoothCamera, bool, false)
			readValue(noAlienPanicMessages, bool, false)
			readValue(alienBleeding, bool, false)

			readValue(keyBattleLeft, SDLKey, SDLK_LEFT)
			readValue(keyBattleRight, SDLKey, SDLK_RIGHT)
			readValue(keyBattleUp, SDLKey, SDLK_UP)
			readValue(keyBattleDown, SDLKey, SDLK_DOWN)
			readValue(keyBattleLevelUp, SDLKey, SDLK_PAGEUP)
			readValue(keyBattleLevelDown, SDLKey, SDLK_PAGEDOWN)
			readValue(keyBattleCenterUnit, SDLKey, SDLK_HOME)
			readValue(keyBattlePrevUnit, SDLKey, SDLK_UNKNOWN)
			readValue(keyBattleNextUnit, SDLKey, SDLK_TAB)
			readValue(keyBattleDeselectUnit, SDLKey, SDLK_BACKSLASH)
			readValue(keyBattleUseLeftHand, SDLKey, SDLK_q)
			readValue(keyBattleUseRightHand, SDLKey, SDLK_e)
			readValue(keyBattleInventory, SDLKey, SDLK_i)
			readValue(keyBattleMap, SDLKey, SDLK_m)
			readValue(keyBattleOptions, SDLKey, SDLK_ESCAPE)
			readValue(keyBattleEndTurn, SDLKey, SDLK_BACKSPACE)
			readValue(keyBattleAbort, SDLKey, SDLK_a)
			readValue(keyBattleStats, SDLKey, SDLK_s)
			readValue(keyBattleKneel, SDLKey, SDLK_k)
			readValue(keyBattleReserveKneel, SDLKey, SDLK_j)
			readValue(keyBattleReload, SDLKey, SDLK_r)
			readValue(keyBattlePersonalLighting, SDLKey, SDLK_l)
			readValue(keyBattleReserveNone, SDLKey, SDLK_F1)
			readValue(keyBattleReserveSnap, SDLKey, SDLK_F2)
			readValue(keyBattleReserveAimed, SDLKey, SDLK_F3)
			readValue(keyBattleReserveAuto, SDLKey, SDLK_F4)
			readValue(keyBattleCenterEnemy1, SDLKey, SDLK_1)
			readValue(keyBattleCenterEnemy2, SDLKey, SDLK_2)
			readValue(keyBattleCenterEnemy3, SDLKey, SDLK_3)
			readValue(keyBattleCenterEnemy4, SDLKey, SDLK_4)
			readValue(keyBattleCenterEnemy5, SDLKey, SDLK_5)
			readValue(keyBattleCenterEnemy6, SDLKey, SDLK_6)
			readValue(keyBattleCenterEnemy7, SDLKey, SDLK_7)
			readValue(keyBattleCenterEnemy8, SDLKey, SDLK_8)
			readValue(keyBattleCenterEnemy9, SDLKey, SDLK_9)
			readValue(keyBattleCenterEnemy10, SDLKey, SDLK_0)
			readValue(keyBattleVoxelView, SDLKey, SDLK_F10)
			readValue(keyBattleZeroTUs, SDLKey, SDLK_DELETE)
			readValue(keyInvCreateTemplate, SDLKey, SDLK_c)
			readValue(keyInvApplyTemplate, SDLKey, SDLK_v)
			readValue(keyInvClear, SDLKey, SDLK_x)
			readValue(keyInvAutoEquip, SDLKey, SDLK_z)
		endGroup();
		beginGroup("OXCE");
			readValue(keyGeoDailyPilotExperience, SDLKey, SDLK_e)
			readValue(keyGeoUfoTracker, SDLKey, SDLK_t)
			readValue(keyGeoTechTreeViewer, SDLKey, SDLK_q)
			readValue(keyGeoGlobalResearch, SDLKey, SDLK_c)
			readValue(keyGeoGlobalProduction, SDLKey, SDLK_p)
			readValue(keyGeoGlobalAlienContainment, SDLKey, SDLK_j)
			readValue(keyGraphsZoomIn, SDLKey, SDLK_KP_PLUS)
			readValue(keyGraphsZoomOut, SDLKey, SDLK_KP_MINUS)
			readValue(keyToggleQuickSearch, SDLKey, SDLK_q)
			readValue(keyInstaSave, SDLKey, SDLK_F6)
			readValue(keyCraftLoadoutSave, SDLKey, SDLK_F5)
			readValue(keyCraftLoadoutLoad, SDLKey, SDLK_F9)
			readValue(keyMarkAllAsSeen, SDLKey, SDLK_x)
			readValue(keySellAll, SDLKey, SDLK_x)
			readValue(keySellAllButOne, SDLKey, SDLK_z)
			readValue(keyTransferAll, SDLKey, SDLK_x)
			readValue(keyRemoveSoldiersFromCraft, SDLKey, SDLK_z)
			readValue(keyRemoveSoldiersFromAllCrafts, SDLKey, SDLK_x)
			readValue(keyRemoveEquipmentFromCraft, SDLKey, SDLK_x)
			readValue(keyRemoveArmorFromCraft, SDLKey, SDLK_z)
			readValue(keyRemoveArmorFromAllCrafts, SDLKey, SDLK_x)
			readValue(keyRemoveSoldiersFromTraining, SDLKey, SDLK_x)
			readValue(keyAddSoldiersToTraining, SDLKey, SDLK_z)
			readValue(keyInventoryArmor, SDLKey, SDLK_a)
			readValue(keyInventoryAvatar, SDLKey, SDLK_m)
			readValue(keyInventoryDiaryLight, SDLKey, SDLK_d)
			readValue(keyInventorySave, SDLKey, SDLK_F5)
			readValue(keyInventoryLoad, SDLKey, SDLK_F9)
			readValue(keyInvSavePersonalEquipment, SDLKey, SDLK_s)
			readValue(keyInvLoadPersonalEquipment, SDLKey, SDLK_l)
			readValue(keyInvShowPersonalEquipment, SDLKey, SDLK_p)
			readValue(keyBattleUnitUp, SDLKey, SDLK_UNKNOWN)
			readValue(keyBattleUnitDown, SDLKey, SDLK_UNKNOWN)
			readValue(keyBattleShowLayers, SDLKey, SDLK_UNKNOWN)
			readValue(keyBattleUseSpecial, SDLKey, SDLK_w)
			readValue(keyBattleActionItem1, SDLKey, SDLK_1)
			readValue(keyBattleActionItem2, SDLKey, SDLK_2)
			readValue(keyBattleActionItem3, SDLKey, SDLK_3)
			readValue(keyBattleActionItem4, SDLKey, SDLK_4)
			readValue(keyBattleActionItem5, SDLKey, SDLK_5)
			readValue(keyNightVisionToggle, SDLKey, SDLK_SCROLLOCK)
			readValue(keyNightVisionHold, SDLKey, SDLK_SPACE)
			readValue(keySelectMusicTrack, SDLKey, SDLK_END)
			readValue(keyBasescapeBuildNewBase, SDLKey, SDLK_n)
			readValue(keyBasescapeBaseInfo, SDLKey, SDLK_i)
			readValue(keyBasescapeSoldiers, SDLKey, SDLK_s)
			readValue(keyBasescapeCrafts, SDLKey, SDLK_e)
			readValue(keyBasescapeFacilities, SDLKey, SDLK_f)
			readValue(keyBasescapeResearch, SDLKey, SDLK_r)
			readValue(keyBasescapeManufacture, SDLKey, SDLK_m)
			readValue(keyBasescapeTransfer, SDLKey, SDLK_t)
			readValue(keyBasescapePurchase, SDLKey, SDLK_p)
			readValue(keyBasescapeSell, SDLKey, SDLK_l)
			readValue(oxceUpdateCheck, bool, false)
			readValue(autosaveSlots, qint32, 1)
			readValue(oxceGeoAutosaveFrequency, qint32, 0)
			readValue(oxceGeoAutosaveSlots, qint32, 1)
			readValue(oxceLinks, bool, false)
			readValue(oxceLinksDisableTextEdit, bool, false)
			readValue(oxceFatFingerLinks, bool, false)
			readValue(oxceBattleTouchButtonsEnabled, bool, false)
			readValue(oxceQuickSearchButton, bool, false)
			readValue(oxceHighlightNewTopics, bool, true)
			readValue(oxcePediaShowClipSize, bool, false)
			readValue(oxcePediaSortResistances, qint32, 0)

			readValue(oxceInterceptTableSize, qint32, 8)
			readValue(oxceEnableSlackingIndicator, bool, true)
			readValue(oxceInterceptGuiMaintenanceTime, qint32, 2)
			readValue(oxceShowETAMode, qint32, 0)
			readValue(oxceUfoLandingAlert, bool, false)
			readValue(oxceRememberDisabledCraftWeapons, bool, false)
			readValue(oxceGeoscapeEventsInstantDelivery, bool, true)
			readValue(oxceShowBaseNameInPopups, bool, false)

			readValue(oxceAlternateCraftEquipmentManagement, bool, false)
			readValue(oxceBaseInfoScaleEnabled, bool, false)
			readValue(oxceResearchScrollSpeed, qint32, 1)
			readValue(oxceResearchScrollSpeedWithCtrl, qint32, 10)
			readValue(oxceManufactureFilterSuppliesOK, bool, false)
			readValue(oxceManufactureScrollSpeed, qint32, 1)
			readValue(oxceManufactureScrollSpeedWithCtrl, qint32, 10)
			readValue(oxcePersonalLayoutIncludingArmor, bool, true)
			readValue(oxceManualPromotions, bool, false)

			readValue(oxceWoundedDefendBaseIf, qint32, 100)
			readValue(oxcePlayBriefingMusicDuringEquipment, bool, false)
			readValue(oxceNightVisionColor, qint32, 5)
			readValue(oxceAutoNightVisionThreshold, qint32, 15)
			readValue(oxceShowAccuracyOnCrosshair, qint32, 1)
			readValue(oxceReactionFireThreshold, qint32, 0)
			readValue(oxceAutoSell, bool, false)
			readValue(oxceAutomaticPromotions, bool, true)
			readValue(oxceEnableOffCentreShooting, bool, false)
			readValue(oxceUniformShootingSpread, bool, false)
			readValue(oxceCrashedOrLanded, qint32, 0)
			readValue(oxceModValidationLevel, qint32, LOG_WARNING)
			readValue(oxceRawScreenShots, bool, false)
			readValue(oxceFirstPersonViewFisheyeProjection, bool, false)
			readValue(oxceThumbButtons, bool, true)
			readValue(oxceThrottleMouseMoveEvent, qint32, 0)
			readValue(oxceDisableThinkingProgressBar, bool, false)

			readValue(oxceEmbeddedOnly, bool, true)
			readValue(oxceListVFSContents, bool, false)
			readValue(oxceEnablePaletteFlickerFix, bool, false)
			readValue(oxceRecommendedOptionsWereSet, bool, false)
			readValue(password, QString, "secret")

			readValue(oxceStartUpTextMode, qint32, 0)

			readValue(oxceGeoscapeDebugLogMaxEntries, qint32, 1000)
			readValue(oxceGeoSlowdownFactor, qint32, 1)
			readValue(oxceGeoShowScoreInsteadOfFunds, bool, false)
			readValue(oxceGeoEnableTrainingIndicator, bool, false)
			readValue(oxceGeoSuppressRedundantHKAlert, bool, true)
			readValue(oxceGeoSuppressLandingWithoutEquipment, bool, false)
			readValue(oxceGeoGoToNearestBase, bool, false)
			readValue(oxceGeoSortCraftByDistanceToTarget, bool, false)

			readValue(oxceBaseInfoDefenseScaleMultiplier, qint32, 100)
			readValue(oxceBaseSoldierTransformationShowOnlyEligible, bool, false)
			readValue(oxceBaseFilterResearchable, bool, false)
			readValue(oxceBaseResearchReorder, bool, false)
			readValue(oxceBaseManufactureFallbackButton, bool, false)
			readValue(oxceBaseManufactureInfinityButton, bool, false)
			readValue(oxceBaseTouchButtons, bool, false)

			readValue(oxceDisableAlienInventory, bool, false)
			readValue(oxceDisableHitLog, bool, false)
			readValue(oxceDisableInventoryTuCost, bool, false)
			readValue(oxceDisableProductionDependencyTree, bool, false)
			readValue(oxceDisableStatsForNerds, bool, false)
			readValue(oxceDisableTechTreeViewer, bool, false)

			readValue(oxceTogglePersonalLightType, qint32, 1)
			readValue(oxceToggleNightVisionType, qint32, 1)
			readValue(oxceToggleBrightnessType, qint32, 0)

			readValue(oxceShowBurningAsWounded, bool, false)
			readValue(oxceDisableInfoOnThrowCursor, bool, false)
			readValue(oxceSwapDontReselectActions, bool, false)
			readValue(oxceEnableUnitResponseSounds, bool, true)
			readValue(oxceHiddenMovementBackgroundChangeFrequency, qint32, 1)
			readValue(oxceInventoryShowUnitSlot, bool, false)
			readValue(oxceReplaceNotesLink, bool, false)

			readValue(oxceInventorySplitScrollButton, bool, false)
			readValue(oxceInventoryDropItemOverPaperdoll, bool, false)
			readValue(oxceInventoryUnloadFixedWeapons, bool, false)

			readValue(oxceMaxEquipmentLayoutTemplates, qint32, 20)
		endGroup();
        beginGroup("Video");
            readValue(displayWidth,  qint32, 640)
            readValue(displayHeight, qint32, 480)
            readValue(windowedModePositionX, qint32, 0)
            readValue(windowedModePositionY, qint32, 0)
        endGroup();
        beginGroup("Audio");
            readValue(soundVolume,  qint32, 2*(MIX_MAX_VOLUME/3))
            readValue(musicVolume,  qint32, 2*(MIX_MAX_VOLUME/3))
            readValue(uiVolume,  qint32, (MIX_MAX_VOLUME/3))
            readValue(audioSampleRate,  qint32, 22050)
            readValue(audioBitDepth,  qint32, 16)
            readValue(audioChunkSize,  qint32, 1024)
        endGroup();
    }

	Options1::~Options1()
	{
		saveSettings();
	}

	void Options1::saveSettings()
	{
		beginGroup("General");
			writeValue(pauseMode, m_pauseMode);
			writeValue(maxFPS, m_maxFPS)
			writeValue(maxFPSInactive, m_maxFPSInactive)
			writeValue(pauseMode, m_pauseMode)
			writeValue(changeValueByMouseWheel, m_changeValueByMouseWheel)
			writeValue(dragScrollTimeTolerance, m_dragScrollTimeTolerance)
			writeValue(dragScrollPixelTolerance, m_dragScrollPixelTolerance)
			writeValue(mousewheelSpeed, m_mousewheelSpeed)
			writeValue(autosaveFrequency, m_autosaveFrequency)

			writeValue(fullscreen, m_fullscreen)
			writeValue(asyncBlit, m_asyncBlit)
			writeValue(playIntro, m_playIntro)
			writeValue(useScaleFilter, m_useScaleFilter)
			writeValue(useHQXFilter, m_useHQXFilter)
			writeValue(useXBRZFilter, m_useXBRZFilter)
			writeValue(useOpenGL, m_useOpenGL)
			writeValue(checkOpenGLErrors, m_checkOpenGLErrors)
			writeValue(vSyncForOpenGL, m_vSyncForOpenGL)
			writeValue(useOpenGLSmoothing, m_useOpenGLSmoothing)

			writeValue(autosave, m_autosave)
			writeValue(allowResize, m_allowResize)
			writeValue(borderless, m_borderless)
			writeValue(debug, m_debug)
			writeValue(debugUi, m_debugUi)
			writeValue(fpsCounter, m_fpsCounter)
			writeValue(newSeedOnLoad, m_newSeedOnLoad)
			writeValue(keepAspectRatio, m_keepAspectRatio)
			writeValue(nonSquarePixelRatio, m_nonSquarePixelRatio)
			writeValue(cursorInBlackBandsInFullscreen, m_cursorInBlackBandsInFullscreen)
			writeValue(cursorInBlackBandsInWindow, m_cursorInBlackBandsInWindow)
			writeValue(cursorInBlackBandsInBorderlessWindow, m_cursorInBlackBandsInBorderlessWindow)
			writeValue(maximizeInfoScreens, m_maximizeInfoScreens)
			writeValue(musicAlwaysLoop, m_musicAlwaysLoop)
			writeValue(StereoSound, m_stereoSound)
			writeValue(verboseLogging, m_verboseLogging)
			writeValue(soldierDiaries, m_soldierDiaries)
			writeValue(touchEnabled, m_touchEnabled)
			writeValue(rootWindowedMode, m_rootWindowedMode)
			writeValue(lazyLoadResources, m_lazyLoadResources)
			writeValue(backgroundMute, m_backgroundMute)
			writeValue(language, m_language)
			writeValue(keyboardMode, m_keyboardMode)
			writeValue(saveOrder, m_saveOrder)
			writeValue(preferredMusic, m_preferredMusic)
			writeValue(preferredSound, m_preferredSound)
			writeValue(preferredVideo, m_preferredVideo)
			writeValue(captureMouse, m_captureMouse)
			writeValue(wordwrap, m_wordwrap)
			writeValue(keyOk, m_keyOk)
			writeValue(keyCancel, m_keyCancel)
			writeValue(keyScreenshot, m_keyScreenshot)
			writeValue(keyFps, m_keyFps)
			writeValue(keyQuickLoad, m_keyQuickLoad)
			writeValue(keyQuickSave, m_keyQuickSave)
			writeValue(useOpenGLShader, m_useOpenGLShader)
		endGroup();
		beginGroup("Geoscape");
			writeValue(geoClockSpeed, m_geoClockSpeed)
			writeValue(dogfightSpeed, m_dogfightSpeed)
			writeValue(geoScrollSpeed, m_geoScrollSpeed)
			writeValue(geoDragScrollButton, m_geoDragScrollButton)
			writeValue(geoscapeScale, m_geoscapeScale)
			writeValue(includePrimeStateInSavedLayout, m_includePrimeStateInSavedLayout)
			writeValue(anytimePsiTraining, m_anytimePsiTraining)
			writeValue(weaponSelfDestruction, m_weaponSelfDestruction)
			writeValue(retainCorpses, m_retainCorpses)
			writeValue(craftLaunchAlways, m_craftLaunchAlways)
			writeValue(globeSurfaceCache, m_globeSurfaceCache)
			writeValue(globeSeasons, m_globeSeasons)
			writeValue(globeDetail, m_globeDetail)
			writeValue(globeRadarLines, m_globeRadarLines)
			writeValue(globeFlightPaths, m_globeFlightPaths)
			writeValue(globeAllRadarsOnBaseBuild, m_globeAllRadarsOnBaseBuild)
			writeValue(storageLimitsEnforced, m_storageLimitsEnforced)
			writeValue(canSellLiveAliens, m_canSellLiveAliens)
			writeValue(canTransferCraftsWhileAirborne, m_canTransferCraftsWhileAirborne)
			writeValue(customInitialBase, m_customInitialBase)
			writeValue(aggressiveRetaliation, m_aggressiveRetaliation)
			writeValue(geoDragScrollInvert, m_geoDragScrollInvert)
			writeValue(allowBuildingQueue, m_allowBuildingQueue)
			writeValue(showFundsOnGeoscape, m_showFundsOnGeoscape)
			writeValue(psiStrengthEval, m_psiStrengthEval)
			writeValue(allowPsiStrengthImprovement, m_allowPsiStrengthImprovement)
			writeValue(fieldPromotions, m_fieldPromotions)
			writeValue(meetingPoint, m_meetingPoint)
			writeValue(keyGeoLeft, m_keyGeoLeft)
			writeValue(keyGeoRight, m_keyGeoRight)
			writeValue(keyGeoUp, m_keyGeoUp)
			writeValue(keyGeoDown, m_keyGeoDown)
			writeValue(keyGeoZoomIn, m_keyGeoZoomIn)
			writeValue(keyGeoZoomOut, m_keyGeoZoomOut)
			writeValue(keyGeoSpeed1, m_keyGeoSpeed1)
			writeValue(keyGeoSpeed2, m_keyGeoSpeed2)
			writeValue(keyGeoSpeed3, m_keyGeoSpeed3)
			writeValue(keyGeoSpeed4, m_keyGeoSpeed4)
			writeValue(keyGeoSpeed5, m_keyGeoSpeed5)
			writeValue(keyGeoSpeed6, m_keyGeoSpeed6)
			writeValue(keyGeoIntercept, m_keyGeoIntercept)
			writeValue(keyGeoBases, m_keyGeoBases)
			writeValue(keyGeoGraphs, m_keyGeoGraphs)
			writeValue(keyGeoUfopedia, m_keyGeoUfopedia)
			writeValue(keyGeoOptions, m_keyGeoOptions)
			writeValue(keyGeoFunding, m_keyGeoFunding)
			writeValue(keyGeoToggleDetail, m_keyGeoToggleDetail)
			writeValue(keyGeoToggleRadar, m_keyGeoToggleRadar)
			writeValue(keyBaseSelect1, m_keyBaseSelect1)
			writeValue(keyBaseSelect2, m_keyBaseSelect2)
			writeValue(keyBaseSelect3, m_keyBaseSelect3)
			writeValue(keyBaseSelect4, m_keyBaseSelect4)
			writeValue(keyBaseSelect5, m_keyBaseSelect5)
			writeValue(keyBaseSelect6, m_keyBaseSelect6)
			writeValue(keyBaseSelect7, m_keyBaseSelect7)
			writeValue(keyBaseSelect8, m_keyBaseSelect8)
		endGroup();
		beginGroup("Battlescape");
			writeValue(battleEdgeScroll, m_battleEdgeScroll)
			writeValue(battleNewPreviewPath, m_battleNewPreviewPath)
			writeValue(battleScrollSpeed, m_battleScrollSpeed)
			writeValue(battleDragScrollButton, m_battleDragScrollButton)
			writeValue(battleFireSpeed, m_battleFireSpeed)
			writeValue(battleXcomSpeed, m_battleXcomSpeed)
			writeValue(battleAlienSpeed, m_battleAlienSpeed)
			writeValue(battleExplosionHeight, m_battleExplosionHeight)
			writeValue(battlescapeScale, m_battlescapeScale)

			writeValue(traceAI, m_traceAI)
			writeValue(sneakyAI, m_sneakyAI)
			writeValue(battleInstantGrenade, m_battleInstantGrenade)
			writeValue(battleNotifyDeath, m_battleNotifyDeath)
			writeValue(battleTooltips, m_battleTooltips)
			writeValue(battleHairBleach, m_battleHairBleach)
			writeValue(battleAutoEnd, m_battleAutoEnd)
			writeValue(strafe, m_strafe)
			writeValue(forceFire, m_forceFire)
			writeValue(showMoreStatsInInventoryView, m_showMoreStatsInInventoryView)
			writeValue(allowPsionicCapture, m_allowPsionicCapture)
			writeValue(skipNextTurnScreen, m_skipNextTurnScreen)
			writeValue(disableAutoEquip, m_disableAutoEquip)
			writeValue(battleDragScrollInvert, m_battleDragScrollInvert)
			writeValue(battleUFOExtenderAccuracy, m_battleUFOExtenderAccuracy)
			writeValue(battleConfirmFireMode, m_battleConfirmFireMode)
			writeValue(battleSmoothCamera, m_battleSmoothCamera)
			writeValue(noAlienPanicMessages, m_noAlienPanicMessages)
			writeValue(alienBleeding, m_alienBleeding)

			writeValue(keyBattleLeft, m_keyBattleLeft)
			writeValue(keyBattleRight, m_keyBattleRight)
			writeValue(keyBattleUp, m_keyBattleUp)
			writeValue(keyBattleDown, m_keyBattleDown)
			writeValue(keyBattleLevelUp, m_keyBattleLevelUp)
			writeValue(keyBattleLevelDown, m_keyBattleLevelDown)
			writeValue(keyBattleCenterUnit, m_keyBattleCenterUnit)
			writeValue(keyBattlePrevUnit, m_keyBattlePrevUnit)
			writeValue(keyBattleNextUnit, m_keyBattleNextUnit)
			writeValue(keyBattleDeselectUnit, m_keyBattleDeselectUnit)
			writeValue(keyBattleUseLeftHand, m_keyBattleUseLeftHand)
			writeValue(keyBattleUseRightHand, m_keyBattleUseRightHand)
			writeValue(keyBattleInventory, m_keyBattleInventory)
			writeValue(keyBattleMap, m_keyBattleMap)
			writeValue(keyBattleOptions, m_keyBattleOptions)
			writeValue(keyBattleEndTurn, m_keyBattleEndTurn)
			writeValue(keyBattleAbort, m_keyBattleAbort)
			writeValue(keyBattleStats, m_keyBattleStats)
			writeValue(keyBattleKneel, m_keyBattleKneel)
			writeValue(keyBattleReserveKneel, m_keyBattleReserveKneel)
			writeValue(keyBattleReload, m_keyBattleReload)
			writeValue(keyBattlePersonalLighting, m_keyBattlePersonalLighting)
			writeValue(keyBattleReserveNone, m_keyBattleReserveNone)
			writeValue(keyBattleReserveSnap, m_keyBattleReserveSnap)
			writeValue(keyBattleReserveAimed, m_keyBattleReserveAimed)
			writeValue(keyBattleReserveAuto, m_keyBattleReserveAuto)
			writeValue(keyBattleCenterEnemy1, m_keyBattleCenterEnemy1)
			writeValue(keyBattleCenterEnemy2, m_keyBattleCenterEnemy2)
			writeValue(keyBattleCenterEnemy3, m_keyBattleCenterEnemy3)
			writeValue(keyBattleCenterEnemy4, m_keyBattleCenterEnemy4)
			writeValue(keyBattleCenterEnemy5, m_keyBattleCenterEnemy5)
			writeValue(keyBattleCenterEnemy6, m_keyBattleCenterEnemy6)
			writeValue(keyBattleCenterEnemy7, m_keyBattleCenterEnemy7)
			writeValue(keyBattleCenterEnemy8, m_keyBattleCenterEnemy8)
			writeValue(keyBattleCenterEnemy9, m_keyBattleCenterEnemy9)
			writeValue(keyBattleCenterEnemy10, m_keyBattleCenterEnemy10)
			writeValue(keyBattleVoxelView, m_keyBattleVoxelView)
			writeValue(keyBattleZeroTUs, m_keyBattleZeroTUs)
			writeValue(keyInvCreateTemplate, m_keyInvCreateTemplate)
			writeValue(keyInvApplyTemplate, m_keyInvApplyTemplate)
			writeValue(keyInvClear, m_keyInvClear)
			writeValue(keyInvAutoEquip, m_keyInvAutoEquip)
		endGroup();
		beginGroup("OXCE");
			writeValue(keyGeoDailyPilotExperience, m_keyGeoDailyPilotExperience)
			writeValue(keyGeoUfoTracker, m_keyGeoUfoTracker)
			writeValue(keyGeoTechTreeViewer, m_keyGeoTechTreeViewer)
			writeValue(keyGeoGlobalResearch, m_keyGeoGlobalResearch)
			writeValue(keyGeoGlobalProduction, m_keyGeoGlobalProduction)
			writeValue(keyGeoGlobalAlienContainment, m_keyGeoGlobalAlienContainment)
			writeValue(keyGraphsZoomIn, m_keyGraphsZoomIn)
			writeValue(keyGraphsZoomOut, m_keyGraphsZoomOut)
			writeValue(keyToggleQuickSearch, m_keyToggleQuickSearch)
			writeValue(keyInstaSave, m_keyInstaSave)
			writeValue(keyCraftLoadoutSave, m_keyCraftLoadoutSave)
			writeValue(keyCraftLoadoutLoad, m_keyCraftLoadoutLoad)
			writeValue(keyMarkAllAsSeen, m_keyMarkAllAsSeen)
			writeValue(keySellAll, m_keySellAll)
			writeValue(keySellAllButOne, m_keySellAllButOne)
			writeValue(keyTransferAll, m_keyTransferAll)
			writeValue(keyRemoveSoldiersFromCraft, m_keyRemoveSoldiersFromCraft)
			writeValue(keyRemoveSoldiersFromAllCrafts, m_keyRemoveSoldiersFromAllCrafts)
			writeValue(keyRemoveEquipmentFromCraft, m_keyRemoveEquipmentFromCraft)
			writeValue(keyRemoveArmorFromCraft, m_keyRemoveArmorFromCraft)
			writeValue(keyRemoveArmorFromAllCrafts, m_keyRemoveArmorFromAllCrafts)
			writeValue(keyRemoveSoldiersFromTraining, m_keyRemoveSoldiersFromTraining)
			writeValue(keyAddSoldiersToTraining, m_keyAddSoldiersToTraining)
			writeValue(keyInventoryArmor, m_keyInventoryArmor)
			writeValue(keyInventoryAvatar, m_keyInventoryAvatar)
			writeValue(keyInventoryDiaryLight, m_keyInventoryDiaryLight)
			writeValue(keyInventorySave, m_keyInventorySave)
			writeValue(keyInventoryLoad, m_keyInventoryLoad)
			writeValue(keyInvSavePersonalEquipment, m_keyInvSavePersonalEquipment)
			writeValue(keyInvLoadPersonalEquipment, m_keyInvLoadPersonalEquipment)
			writeValue(keyInvShowPersonalEquipment, m_keyInvShowPersonalEquipment)
			writeValue(keyBattleUnitUp, m_keyBattleUnitUp)
			writeValue(keyBattleUnitDown, m_keyBattleUnitDown)
			writeValue(keyBattleShowLayers, m_keyBattleShowLayers)
			writeValue(keyBattleUseSpecial, m_keyBattleUseSpecial)
			writeValue(keyBattleActionItem1, m_keyBattleActionItem1)
			writeValue(keyBattleActionItem2, m_keyBattleActionItem2)
			writeValue(keyBattleActionItem3, m_keyBattleActionItem3)
			writeValue(keyBattleActionItem4, m_keyBattleActionItem4)
			writeValue(keyBattleActionItem5, m_keyBattleActionItem5)
			writeValue(keyNightVisionToggle, m_keyNightVisionToggle)
			writeValue(keyNightVisionHold, m_keyNightVisionHold)
			writeValue(keySelectMusicTrack, m_keySelectMusicTrack)
			writeValue(keyBasescapeBuildNewBase, m_keyBasescapeBuildNewBase)
			writeValue(keyBasescapeBaseInfo, m_keyBasescapeBaseInfo)
			writeValue(keyBasescapeSoldiers, m_keyBasescapeSoldiers)
			writeValue(keyBasescapeCrafts, m_keyBasescapeCrafts)
			writeValue(keyBasescapeFacilities, m_keyBasescapeFacilities)
			writeValue(keyBasescapeResearch, m_keyBasescapeResearch)
			writeValue(keyBasescapeManufacture, m_keyBasescapeManufacture)
			writeValue(keyBasescapeTransfer, m_keyBasescapeTransfer)
			writeValue(keyBasescapePurchase, m_keyBasescapePurchase)
			writeValue(keyBasescapeSell, m_keyBasescapeSell)
			writeValue(oxceUpdateCheck, m_oxceUpdateCheck)
			writeValue(autosaveSlots, m_autosaveSlots)
			writeValue(oxceGeoAutosaveFrequency, m_oxceGeoAutosaveFrequency)
			writeValue(oxceGeoAutosaveSlots, m_oxceGeoAutosaveSlots)
			writeValue(oxceLinks, m_oxceLinks)
			writeValue(oxceLinksDisableTextEdit, m_oxceLinksDisableTextEdit)
			writeValue(oxceFatFingerLinks, m_oxceFatFingerLinks)
			writeValue(oxceBattleTouchButtonsEnabled, m_oxceBattleTouchButtonsEnabled)
			writeValue(oxceQuickSearchButton, m_oxceQuickSearchButton)
			writeValue(oxceHighlightNewTopics, m_oxceHighlightNewTopics)
			writeValue(oxcePediaShowClipSize, m_oxcePediaShowClipSize)
			writeValue(oxcePediaSortResistances, m_oxcePediaSortResistances)

			writeValue(oxceInterceptTableSize, m_oxceInterceptTableSize)
			writeValue(oxceEnableSlackingIndicator, m_oxceEnableSlackingIndicator)
			writeValue(oxceInterceptGuiMaintenanceTime, m_oxceInterceptGuiMaintenanceTime)
			writeValue(oxceShowETAMode, m_oxceShowETAMode)
			writeValue(oxceUfoLandingAlert, m_oxceUfoLandingAlert)
			writeValue(oxceRememberDisabledCraftWeapons, m_oxceRememberDisabledCraftWeapons)
			writeValue(oxceGeoscapeEventsInstantDelivery, m_oxceGeoscapeEventsInstantDelivery)
			writeValue(oxceShowBaseNameInPopups, m_oxceShowBaseNameInPopups)

			writeValue(oxceAlternateCraftEquipmentManagement, m_oxceAlternateCraftEquipmentManagement)
			writeValue(oxceBaseInfoScaleEnabled, m_oxceBaseInfoScaleEnabled)
			writeValue(oxceResearchScrollSpeed, m_oxceResearchScrollSpeed)
			writeValue(oxceResearchScrollSpeedWithCtrl, m_oxceResearchScrollSpeedWithCtrl)
			writeValue(oxceManufactureFilterSuppliesOK, m_oxceManufactureFilterSuppliesOK)
			writeValue(oxceManufactureScrollSpeed, m_oxceManufactureScrollSpeed)
			writeValue(oxceManufactureScrollSpeedWithCtrl, m_oxceManufactureScrollSpeedWithCtrl)
			writeValue(oxcePersonalLayoutIncludingArmor, m_oxcePersonalLayoutIncludingArmor)
			writeValue(oxceManualPromotions, m_oxceManualPromotions)

			writeValue(oxceWoundedDefendBaseIf, m_oxceWoundedDefendBaseIf)
			writeValue(oxcePlayBriefingMusicDuringEquipment, m_oxcePlayBriefingMusicDuringEquipment)
			writeValue(oxceNightVisionColor, m_oxceNightVisionColor)
			writeValue(oxceAutoNightVisionThreshold, m_oxceAutoNightVisionThreshold)
			writeValue(oxceShowAccuracyOnCrosshair, m_oxceShowAccuracyOnCrosshair)
			writeValue(oxceReactionFireThreshold, m_oxceReactionFireThreshold)
			writeValue(oxceAutoSell, m_oxceAutoSell)
			writeValue(oxceAutomaticPromotions, m_oxceAutomaticPromotions)
			writeValue(oxceEnableOffCentreShooting, m_oxceEnableOffCentreShooting)
			writeValue(oxceUniformShootingSpread, m_oxceUniformShootingSpread)
			writeValue(oxceCrashedOrLanded, m_oxceCrashedOrLanded)
			writeValue(oxceModValidationLevel, m_oxceModValidationLevel)
			writeValue(oxceRawScreenShots, m_oxceRawScreenShots)
			writeValue(oxceFirstPersonViewFisheyeProjection, m_oxceFirstPersonViewFisheyeProjection)
			writeValue(oxceThumbButtons, m_oxceThumbButtons)
			writeValue(oxceThrottleMouseMoveEvent, m_oxceThrottleMouseMoveEvent)
			writeValue(oxceDisableThinkingProgressBar, m_oxceDisableThinkingProgressBar)

			writeValue(oxceEmbeddedOnly, m_oxceEmbeddedOnly)
			writeValue(oxceListVFSContents, m_oxceListVFSContents)
			writeValue(oxceEnablePaletteFlickerFix, m_oxceEnablePaletteFlickerFix)
			writeValue(oxceRecommendedOptionsWereSet, m_oxceRecommendedOptionsWereSet)
			writeValue(password, m_password)

			writeValue(oxceStartUpTextMode, m_oxceStartUpTextMode)

			writeValue(oxceGeoscapeDebugLogMaxEntries, m_oxceGeoscapeDebugLogMaxEntries)
			writeValue(oxceGeoSlowdownFactor, m_oxceGeoSlowdownFactor)
			writeValue(oxceGeoShowScoreInsteadOfFunds, m_oxceGeoShowScoreInsteadOfFunds)
			writeValue(oxceGeoEnableTrainingIndicator, m_oxceGeoEnableTrainingIndicator)
			writeValue(oxceGeoSuppressRedundantHKAlert, m_oxceGeoSuppressRedundantHKAlert)
			writeValue(oxceGeoSuppressLandingWithoutEquipment, m_oxceGeoSuppressLandingWithoutEquipment)
			writeValue(oxceGeoGoToNearestBase, m_oxceGeoGoToNearestBase)
			writeValue(oxceGeoSortCraftByDistanceToTarget, m_oxceGeoSortCraftByDistanceToTarget)

			writeValue(oxceBaseInfoDefenseScaleMultiplier, m_oxceBaseInfoDefenseScaleMultiplier)
			writeValue(oxceBaseSoldierTransformationShowOnlyEligible, m_oxceBaseSoldierTransformationShowOnlyEligible)
			writeValue(oxceBaseFilterResearchable, m_oxceBaseFilterResearchable)
			writeValue(oxceBaseResearchReorder, m_oxceBaseResearchReorder)
			writeValue(oxceBaseManufactureFallbackButton, m_oxceBaseManufactureFallbackButton)
			writeValue(oxceBaseManufactureInfinityButton, m_oxceBaseManufactureInfinityButton)
			writeValue(oxceBaseTouchButtons, m_oxceBaseTouchButtons)

			writeValue(oxceDisableAlienInventory, m_oxceDisableAlienInventory)
			writeValue(oxceDisableHitLog, m_oxceDisableHitLog)
			writeValue(oxceDisableInventoryTuCost, m_oxceDisableInventoryTuCost)
			writeValue(oxceDisableProductionDependencyTree, m_oxceDisableProductionDependencyTree)
			writeValue(oxceDisableStatsForNerds, m_oxceDisableStatsForNerds)
			writeValue(oxceDisableTechTreeViewer, m_oxceDisableTechTreeViewer)

			writeValue(oxceTogglePersonalLightType, m_oxceTogglePersonalLightType)
			writeValue(oxceToggleNightVisionType, m_oxceToggleNightVisionType)
			writeValue(oxceToggleBrightnessType, m_oxceToggleBrightnessType)

			writeValue(oxceShowBurningAsWounded, m_oxceShowBurningAsWounded)
			writeValue(oxceDisableInfoOnThrowCursor, m_oxceDisableInfoOnThrowCursor)
			writeValue(oxceSwapDontReselectActions, m_oxceSwapDontReselectActions)
			writeValue(oxceEnableUnitResponseSounds, m_oxceEnableUnitResponseSounds)
			writeValue(oxceHiddenMovementBackgroundChangeFrequency, m_oxceHiddenMovementBackgroundChangeFrequency)
			writeValue(oxceInventoryShowUnitSlot, m_oxceInventoryShowUnitSlot)
			writeValue(oxceReplaceNotesLink, m_oxceReplaceNotesLink)

			writeValue(oxceInventorySplitScrollButton, m_oxceInventorySplitScrollButton)
			writeValue(oxceInventoryDropItemOverPaperdoll, m_oxceInventoryDropItemOverPaperdoll)
			writeValue(oxceInventoryUnloadFixedWeapons, m_oxceInventoryUnloadFixedWeapons)

			writeValue(oxceMaxEquipmentLayoutTemplates, m_oxceMaxEquipmentLayoutTemplates)
		endGroup();
		beginGroup("Video");
			writeValue(displayWidth, m_displayWidth)
			writeValue(displayHeight, m_displayHeight)
			writeValue(windowedModePositionX, m_windowedModePositionX)
			writeValue(windowedModePositionY, m_windowedModePositionY)
		endGroup();
		beginGroup("Audio");
			writeValue(soundVolume, m_soundVolume)
			writeValue(musicVolume, m_musicVolume)
			writeValue(uiVolume, m_uiVolume)
			writeValue(audioSampleRate, m_audioSampleRate)
			writeValue(audioBitDepth, m_audioBitDepth)
			writeValue(audioChunkSize, m_audioChunkSize)
		endGroup();

		sync();
	}
}
