#pragma once

#ifdef __cplusplus
#include <sstream>
#include <vector>
#include <list>
#include <string>
#include <map>
#include <set>
#include <locale>
#include <unordered_map>
#include <tuple>
#include <algorithm>
#include <cmath>
#include <unordered_set>
#include <stdexcept>
#include <cstdint>
#include <climits>
#include <memory>
#include <cstring>
#include <functional>
#include <utility>
#include <stdint.h>
#include <cfloat>
#include <cassert>
#include <QString>
#include <QVector>
#include <QDebug>
#endif